package com.tecknobit.glidercore.enums

import kotlinx.serialization.Serializable

/**
 * The `PasswordType` are the available types of the password can be stored in the system
 */
@Serializable
enum class PasswordType {

    /**
     * `GENERATED` the password has been generated by the system
     */
    GENERATED,

    /**
     * `INSERTED` the password has been inserted by the user
     */
    INSERTED

}